### ISSUE TITLE
Getting an errors after installing pod into my fresh project.

### ISSUE THREAD

**Issue by KheniDharmesh** [Placenote/PlacenoteSDK-iOS#46]
I have added below pod into my new Swift project.

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test

pod 'PlacenoteSDK'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

And I am getting this errors after `pod install`.

I have also installed `Homebrew` via terminal with `brew install git-lfs` command.

now I am running into below errors. 

![screen shot 2018-07-21 at 1 09 32 pm](https://user-images.githubusercontent.com/22586229/43033391-5647e0a0-8ce7-11e8-901b-c959f32dc2b0.png)

I have also tried with clear derived data, clean project, and restart Xcode. But it is not working. Please help.

**Comment by Parameshvadivel** [comment]
Hey, have you found any solution?

**Comment by KheniDharmesh** [comment]
Yes I run it on device and it works!!

**Comment by Parameshvadivel** [comment]
have you faced this issue? This warnings are shown in my console...

```
2018-10-26 14:16:41.395581+0530 PlacenoteSDKExample[362:23611] [DYMTLInitPlatform] platform initialization successful
2018-10-26 14:16:42.549823+0530 PlacenoteSDKExample[362:23475] initializing SDK
2018-10-26 14:16:42.599879+0530 PlacenoteSDKExample[362:23475] Metal GPU Frame Capture Enabled
2018-10-26 14:16:42.610816+0530 PlacenoteSDKExample[362:23475] Metal API Validation Enabled
2018-10-26 14:16:42.903210+0530 PlacenoteSDKExample[362:23475] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-10-26 14:16:42.909228+0530 PlacenoteSDKExample[362:23475] [MC] Reading from public effective user settings.
Map size: 1
Map size: 1
Map size: 1
Map size: 1
SDK is not initialized
SDK is not initialized
SDK is not initialized
[2018-10-26 14:16:43.538] [multisink] [error] libPlacenote: PNGetStatus: Vertical Mapping SDK not initialized
2018-10-26 14:16:43.539031+0530 PlacenoteSDKExample[362:23475] Unknown status: -1
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
[2018-10-26 14:16:44.291] [multisink] [error] libPlacenote: PNGetStatus: Vertical Mapping SDK not initialized
2018-10-26 14:16:44.291699+0530 PlacenoteSDKExample[362:23475] Unknown status: -1
[2018-10-26 14:16:44.508] [multisink] [error] libPlacenote: PNGetStatus: Vertical Mapping SDK not initialized
2018-10-26 14:16:44.509033+0530 PlacenoteSDKExample[362:23475] Unknown status: -1
SDK is not initialized
SDK is not initialized
SDK is not initialized
SDK is not initialized
```

**Comment by pmukherj** [comment]
Issue fixed in project settings of custom project.

**Comment by kmdnampoothiri** [comment]
> Yes I run it on device and it works!!

Can you tell me how you fixed this issue? I am getting exactly same issue. I have tried copy SDK from existing Placenote sample application. Still not working. 8.3 MB is the size of Placenote.framework size. 

Here is the log;

Undefined symbols for architecture arm64:
  "_PNSetFrame", referenced from:
      _setFrameNative in LibPlacenote.o
  "_PNGetPose", referenced from:
      _getPoseNative in LibPlacenote.o
  "_PNSetIntrinsics", referenced from:
      _setIntrinsicsNative in LibPlacenote.o
  "_PNInitialize", referenced from:
      _initializeSDK in LibPlacenote.o
  "_PNStartRecordDataset", referenced from:
      PlacenoteSDK.LibPlacenote.startReportRecord(uploadProgressCb: (Swift.Bool, Swift.Bool, Swift.Float) -> ()) -> () in LibPlacenote.o
  "_PNGetMetadata", referenced from:
      PlacenoteSDK.LibPlacenote.getMapMetadata(mapId: Swift.String, getMetadataCb: (Swift.Bool, PlacenoteSDK.LibPlacenote.MapMetadata) -> ()) -> () in LibPlacenote.o
  "_PNListMaps", referenced from:
      PlacenoteSDK.LibPlacenote.fetchMapList(listCb: (Swift.Bool, [Swift.String : PlacenoteSDK.LibPlacenote.MapMetadata]) -> ()) -> () in LibPlacenote.o
  "_PNGetAllLandmarks", referenced from:
      PlacenoteSDK.LibPlacenote.getAllLandmarks() -> [__C.PNFeaturePoint_t] in LibPlacenote.o
  "_PNSearchMaps", referenced from:
      PlacenoteSDK.LibPlacenote.searchMaps(searchParams: PlacenoteSDK.LibPlacenote.MapSearch, listCb: (Swift.Bool, [Swift.String : PlacenoteSDK.LibPlacenote.MapMetadata]) -> ()) -> () in LibPlacenote.o
  "_PNSaveMap", referenced from:
      closure #1 (Swift.UnsafeMutablePointer<__C.PNCallbackResult_t>?, Swift.UnsafeMutableRawPointer?) -> () in PlacenoteSDK.LibPlacenote.saveMap(savedCb: (Swift.String?) -> (), uploadProgressCb: (Swift.Bool, Swift.Bool, Swift.Float) -> ()) -> () in LibPlacenote.o
  "_PNAddMap", referenced from:
      PlacenoteSDK.LibPlacenote.saveMap(savedCb: (Swift.String?) -> (), uploadProgressCb: (Swift.Bool, Swift.Bool, Swift.Float) -> ()) -> () in LibPlacenote.o
  "_PNStopSession", referenced from:
      PlacenoteSDK.LibPlacenote.stopSession() -> () in LibPlacenote.o
  "_PNShutdown", referenced from:
      PlacenoteSDK.LibPlacenote.shutdown() -> () in LibPlacenote.o
  "_PNGetStatus", referenced from:
      PlacenoteSDK.LibPlacenote.getMappingStatus() -> PlacenoteSDK.LibPlacenote.MappingStatus in LibPlacenote.o
  "_PNGetTrackedLandmarks", referenced from:
      PlacenoteSDK.LibPlacenote.getTrackedLandmarks() -> [__C.PNFeaturePoint_t] in LibPlacenote.o
  "_PNLoadMap", referenced from:
      PlacenoteSDK.LibPlacenote.loadMap(mapId: Swift.String, downloadProgressCb: (Swift.Bool, Swift.Bool, Swift.Float) -> ()) -> () in LibPlacenote.o
  "_PNSetMetadata", referenced from:
      PlacenoteSDK.LibPlacenote.setMapMetadata(mapId: Swift.String, metadata: PlacenoteSDK.LibPlacenote.MapMetadataSettable, metadataSavedCb: (Swift.Bool) -> ()) -> Swift.Bool in LibPlacenote.o
  "_PNDeleteMap", referenced from:
      PlacenoteSDK.LibPlacenote.deleteMap(mapId: Swift.String, deletedCb: (Swift.Bool) -> ()) -> () in LibPlacenote.o
  "_PNStartSession", referenced from:
      PlacenoteSDK.LibPlacenote.startSession(extend: Swift.Bool) -> () in LibPlacenote.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
